- hosts: all
  vars:
    proxy_env:
      http_proxy:
      https_proxy:
      ftp_proxy:
    gds_env:
      GADDIR: /usr/share/grads/
  sudo: yes
  tasks:
    # 1. java1.5 から 1.6にする
    # 2. ansible/gds.xml のdatasetのfileのパスを書き換える。(デフォルトは/var/lib/gds-2.0/data/S etc)


    # FIXME: 問題があれば80だけなど
    - name: stop iptables
      service: name=iptables state=stopped


    - name: fetch epel rpm
      get_url: url=http://ftp.jaist.ac.jp/pub/Linux/Fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-5-4.noarch.rpm
      environment: proxy_env

    - name: install epel
      yum: name=/tmp/epel-release-5-4.noarch.rpm state=present
      environment: proxy_env

    - name: install libselinux-python
      yum: name=libselinux-python
      environment: proxy_env

    - name: install unzip
      yum: name=unzip
      environment: proxy_env


    # GDS
    - name: install GrADS
      yum: name=grads
      environment: proxy_env

    - name: fetch GDS
      get_url: url=ftp://cola.gmu.edu/grads/gds/gds-2.0.tar.gz dest=/tmp/gds-2.0.tar.gz
      environment: proxy_env

    - name: unarchive GDS
      command: tar -xzf gds-2.0.tar.gz -C /var/lib/ chdir=/tmp creates=/var/lib/gds-2.0

    - name: add gds.xml
      copy: src=gds.xml dest=/var/lib/gds-2.0/gds.xml

    - name: add server.xml
      copy: src=server.xml dest=/var/lib/gds-2.0/tomcat4/conf/server.xml

    - name: add jetty-gds.xml
      copy: src=jetty-gds.xml dest=/var/lib/gds-2.0/jetty4/jetty-gds.xml


    # apache
    - name: install httpd
      yum: name=httpd state=present
      environment: proxy_env

    - name: add proxy_ajp settings
      copy: src=proxy_ajp.conf dest=/etc/httpd/conf.d/proxy_ajp.conf

    - name: add cors settings
      copy: src=cors.conf dest=/etc/httpd/conf.d/cors.conf


    # restart
    - name: restart httpd
      service: name=httpd enabled=yes state=restarted

    - name: restart gds
      command: /var/lib/gds-2.0/rebootserver
