- hosts: all
  handlers:
    - name: restart iptables
      service: name=iptables state=restarted

    - name: restart tomcat
      service: name=tomcat6 enabled=yes state=restarted

    - name: restart httpd
      service: name=httpd enabled=yes state=restarted
  tasks:
    - name: fetch epel rpm
      get_url: url=http://ftp.jaist.ac.jp/pub/Linux/Fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-6-8.noarch.rpm
      environment: proxy_env

    - name: install epel
      yum: name=/tmp/epel-release-6-8.noarch.rpm state=present
      environment: proxy_env

    - name: install packages from yum
      yum: name={{item}} state=installed
      environment: proxy_env
      with_items:
        - libselinux-python
        - unzip


    # Tomcat6
    - name: install tomcat6
      yum: name=tomcat6
      notify: restart tomcat
      environment: proxy_env

    - name: add tomcat options
      copy: src=tomcat6.conf dest=/etc/tomcat6/tomcat6.conf


    # GDS
    - name: install GrADS
      yum: name=grads
      environment: proxy_env

    - name: fetch GDS
      get_url: url=ftp://cola.gmu.edu/grads/gds/gds-2.0.tar.gz dest=/tmp/gds-2.0.tar.gz
      environment: proxy_env

    - name: unarchive GDS
      command: tar -xzf gds-2.0.tar.gz -C /var/lib/ chdir=/tmp creates=/var/lib/gds-2.0

    - name: install dods
      command: cp -r /var/lib/gds-2.0/tomcat4/webapps/dods /var/lib/tomcat6/webapps/dods creates=/var/lib/tomcat6/webapps/dods
      notify: restart tomcat

    - name: add gds.xml
      template: src=templates/gds.xml dest=/var/lib/gds-2.0/gds.xml mode=644
      notify: restart tomcat


    # apache
    - name: install httpd
      yum: name=httpd state=present
      notify: restart httpd
      environment: proxy_env

    - name: add proxy_ajp settings
      copy: src=proxy_ajp.conf dest=/etc/httpd/conf.d/proxy_ajp.conf
      notify: restart httpd

    - name: add cors settings
      copy: src=cors.conf dest=/etc/httpd/conf.d/cors.conf
      notify: restart httpd

    - name: insert iptables rule
      lineinfile: dest=/etc/sysconfig/iptables state=present regexp="80"
                  insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport 80 -j ACCEPT"
      notify: restart iptables
