- hosts: all
  user: vagrant
  vars:
    gds_env:
      GADDIR: /usr/share/grads/
  sudo: yes
  tasks:
    - name: fetch epel rpm
      get_url: url=http://ftp.jaist.ac.jp/pub/Linux/Fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-5-4.noarch.rpm

    - name: install epel
      yum: name=/tmp/epel-release-5-4.noarch.rpm state=present

    - name: install libselinux-python
      yum: name=libselinux-python

    - name: install unzip
      yum: name=unzip


    - name: remove java 1.5
      yum: name=java state=removed

    - name: install java 1.6
      yum: name=java-1.6.0-openjdk-devel.x86_64 state=latest


    # GDS
    - name: install GrADS
      yum: name=grads

    - name: fetch GDS
      get_url: url=ftp://cola.gmu.edu/grads/gds/gds-2.0.tar.gz dest=/tmp/gds-2.0.tar.gz

    - name: unarchive GDS
      command: tar -xzf gds-2.0.tar.gz -C /var/lib/ chdir=/tmp creates=/var/lib/gds-2.0

    - name: add gds.xml
      copy: src=gds.xml dest=/var/lib/gds-2.0/gds.xml

    - name: add server.xml
      copy: src=server.xml dest=/var/lib/gds-2.0/tomcat4/conf/server.xml

    - name: add jetty-gds.xml
      copy: src=jetty-gds.xml dest=/var/lib/gds-2.0/jetty4/jetty-gds.xml

    - name: add S
      copy: src=S.zip dest=/tmp/S.zip

    - name: unarchive S
      command: unzip -o /tmp/S.zip -d /var/lib/gds-2.0


    # apache
    - name: install httpd
      yum: name=httpd state=present

    - name: add proxy_ajp settings
      copy: src=proxy_ajp.conf dest=/etc/httpd/conf.d/proxy_ajp.conf

    - name: add cors settings
      copy: src=cors.conf dest=/etc/httpd/conf.d/cors.conf


    # restart
    - name: restart httpd
      service: name=httpd enabled=yes state=restarted

    - name: restart gds
      command: /var/lib/gds-2.0/rebootserver
